### ISSUE TITLE
Wrong shortcut in the Mixer strip

### ISSUE THREAD

**Issue by relascope** [brunoruviaro/ardour4-tutorial#29]
The Mixer Strip from Top to Bottom
If you don’t see it, hit “Control” + “E” to display the Editor Mixer Strip.

It should be "Shift + E"

**Comment by brunoruviaro** [comment]
Thanks! I will fix this in the upcoming Ardour 5 version of the tutorial
(hopefully Summer 2017).

B

**Comment by brunoruviaro** [comment]
Fixed.
